### ISSUE TITLE
Class 'SKONIKS\Centrifugo\Centrifugo' not found

### ISSUE THREAD

**Issue by fearrr** [skoniks/php_cent#1]
ErrorException in AliasLoader.php line 66:
Class 'SKONIKS\Centrifugo\Centrifugo' not found

в config/app.php
```
'Centrifugo'=> SKONIKS\Centrifugo\Centrifugo::class,
```

в контроллере
```
use Centrifugo as Centrifuge;
```

**Comment by skoniks** [comment]
Исправлено в v2.4

**Comment by ghost** [comment]
Same issue for v2.4 

> ErrorException in AliasLoader.php line 66:
Class 'SKONIKS\Centrifuge\Centrifuge' not found

**Comment by skoniks** [comment]
@piotrlis check readme and find this
[https://github.com/skoniks/php_cent#alias-additions-configappphp](https://github.com/skoniks/php_cent#alias-additions-configappphp)
